### PR TITLE
Rails Api endoint

### PR DESCRIPTION
**Pull request by Bria222**
# In this PR, I did the following:

 - Created a new Rails API app called 'Greeting-backend-rails'.
 - Initialized your project with Git.
 - Made sure that the project has a Postgres database set up.
 - Created a table for storing  messages and create 5 different greetings.
 - Created an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### INVALID 🛑 

 Great work submitting your project for review. You have made a good effort. However, I cannot continue to review your project because of the following reason. ⬇️ 

- [ ] The link you have provided for your front-end application is broken. remember you have to provide a link that points to the frontend application for this project. Kindly correct this and submit your project for another review.

**Comment by Bria222** [comment]
@peterrobert  i have added the frontend url i has mispelled it while pushing

**Comment by Bria222** [comment]
https://github.com/Bria222/Greeting-frontend-react/pull/1

**Review by TedLivist — APPROVED** [review]
## STATUS: APPROVED ✔️ ✔️

Hi @Bria222,

✔️ Frontend and backend apps are well integrated

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by jerryowusu — COMMENTED** [review]
Hi @Bria222 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

CookedDelectableDolphin-size_restricted


## Highlights
Great effort so far :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
